package com.jash.dmgame.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jash.dmgame.entities.TypeEntity;
import com.jash.dmgame.entities.ChapterEntity;

import com.jash.dmgame.dao.TypeEntityDao;
import com.jash.dmgame.dao.ChapterEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig typeEntityDaoConfig;
    private final DaoConfig chapterEntityDaoConfig;

    private final TypeEntityDao typeEntityDao;
    private final ChapterEntityDao chapterEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        typeEntityDaoConfig = daoConfigMap.get(TypeEntityDao.class).clone();
        typeEntityDaoConfig.initIdentityScope(type);

        chapterEntityDaoConfig = daoConfigMap.get(ChapterEntityDao.class).clone();
        chapterEntityDaoConfig.initIdentityScope(type);

        typeEntityDao = new TypeEntityDao(typeEntityDaoConfig, this);
        chapterEntityDao = new ChapterEntityDao(chapterEntityDaoConfig, this);

        registerDao(TypeEntity.class, typeEntityDao);
        registerDao(ChapterEntity.class, chapterEntityDao);
    }
    
    public void clear() {
        typeEntityDaoConfig.getIdentityScope().clear();
        chapterEntityDaoConfig.getIdentityScope().clear();
    }

    public TypeEntityDao getTypeEntityDao() {
        return typeEntityDao;
    }

    public ChapterEntityDao getChapterEntityDao() {
        return chapterEntityDao;
    }

}
