package com.jash.dmgame.entities;

import java.util.List;
import com.jash.dmgame.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.jash.dmgame.dao.ChapterEntityDao;
import com.jash.dmgame.dao.TypeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TYPE_ENTITY".
 */
public class TypeEntity {

    private Long id;
    private String typeName;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TypeEntityDao myDao;

    private List<ChapterEntity> chapterEntityList;

    public TypeEntity() {
    }

    public TypeEntity(Long id) {
        this.id = id;
    }

    public TypeEntity(Long id, String typeName) {
        this.id = id;
        this.typeName = typeName;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTypeEntityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ChapterEntity> getChapterEntityList() {
        if (chapterEntityList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ChapterEntityDao targetDao = daoSession.getChapterEntityDao();
            List<ChapterEntity> chapterEntityListNew = targetDao._queryTypeEntity_ChapterEntityList(id);
            synchronized (this) {
                if(chapterEntityList == null) {
                    chapterEntityList = chapterEntityListNew;
                }
            }
        }
        return chapterEntityList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetChapterEntityList() {
        chapterEntityList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
